---
# PV for AWS EBS Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e5e7dbd4c4d56ecc

---
# PVC for AWS EBS Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---
# Pod using the PVC
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ebs
spec:
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-static-pvc
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-volume
          mountPath: /usr/share/nginx/html          
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c