---
# Storages class for EBS dynamic provsioning
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
reclaimPolicy: Retain      # Volume along with data will be retained even after PVC deletion, Delete- volume is deleted when pvc is deleted
provisioner: ebs.csi.aws.com  # Uses AWS EBS CSI driver for dynamically create PVs
volumeBindingMode: WaitForFirstConsumer 

---
# PVC for AWS EBS Volume which uses above storage class for dynamic provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi

---
# Pod using the PVC
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: ebs-claim
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-volume
          mountPath: /usr/share/nginx/html