---
# Storage class for EFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-090955993cf897055
  basePath: "/dynamic_provisioning"
  directoryPerms: "700"
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
# PVC 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
# Pod
# apiVersion: v1
# kind: Pod
# metadata:
#   name: efs-app
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: persistent-storage
#       mountPath: /usr/share/nginx/html
#   volumes:
#   - name: persistent-storage
#     persistentVolumeClaim:
#       claimName: efs-dynamic