apiVersion: v1
kind: Pod
metadata: 
  name: frontend-pod
  namespace: roboshop
  labels:
    name: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.29.4
    ports:
    - containerPort: 80
