apiVersion: eksctl.io/v1alpha5
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
  labels:
    environment: development
spec:
  containers:
  - name: nginx
    image: nginx:1.29.4
  - name: nodejs
    image: node:20
    