apiVersion: v1
kind: Pod
metadata:
  name: resource-limts-test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # Mentioned resources will be reserved on the node for the container
      requests:
        memory: 50Mi
        cpu: 100m
    # Container won't consume more than the specified limits
      limits: 
        memory: 100Mi
        cpu: 150m