apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "Kubernetes"
    - name: concept
      value: "environment variables"