apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    # This way we can import all the keys from Secret as env variables
    # envFrom:
    # - secretRef:    # reference to Secret
    #     name: test-secret
    # This is more controlled way. We can import the keys we want from Secret as env variables.
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: DB_USER