---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None
  selector:
    name: headless
    purpose: demo
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  # labels for deployment. These can be different from pod labels and selector. These are just for deployment identification
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 3
  # selector to identify pods managed by deployment
  selector:
    matchLabels:
      name: headless
      purpose: demo
  template:
    metadata:
      # pod template labels. Should match selector
      labels:
       name: headless
       purpose: demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.1